### PR TITLE
change accept_any_schema to options

### LINKED ISSUE #323: [Bug] insert column is null when select column name is not equal to the sink table column name
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

25.X

### What's Wrong?

use example_db;
CREATE TABLE table1
(
    siteid INT DEFAULT '10',
    citycode SMALLINT,
    username VARCHAR(32) DEFAULT '',
    pv BIGINT SUM DEFAULT '0'
)
AGGREGATE KEY(siteid, citycode, username)
DISTRIBUTED BY HASH(siteid) BUCKETS 10
PROPERTIES("replication_num" = "1");

CREATE OR REPLACE TEMPORARY VIEW table1
USING doris
OPTIONS (
table.identifier="example_db.table1",
fenodes="xxx",
user="root",
password="xx"
);

CREATE OR REPLACE TEMPORARY VIEW table2
USING doris
OPTIONS (
table.identifier="example_db.table2",
fenodes="xxx",
user="root",
password="xx"
);

insert into table2 select siteid, citycode + 1, username, pv + 1 from table1

this insert sql cause the colum citycode and pv has no data

### What You Expected?

expect the column has correct data.

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wanggx**
[[# Proposed changes

Issue Number: close #323 

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...
]
(https://github.com/apache/doris-spark-connector/issues/323)](https://github.com/apache/doris-spark-connector/issues/323)

### CODE REVIEW

**Comment by wanggx** [comment]
https://github.com/apache/doris-spark-connector/issues/323

File: spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/sql/DorisAnySchemaITCase.scala [hunk 1]
```diff
@@ -0,0 +1,235 @@
...
+      """
+        |insert into table2 values (0, 0, "user1", 100), (1, 0, "user2", 100),(2, 1, "user3", 100),(3, 0, "user2", 200)
+        |""".stripMargin)
+
+    spark.sql(
+      """
+        |insert into test_lh select siteid, citycode + 1, username, pv + 1 from table2
+        |""".stripMargin)
+
+    spark.stop()
```
Comment (JNSimba) [inline spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/sql/DorisAnySchemaITCase.scala:149]: You need to add validation to ensure that the data inserted is in line with expectations, similar to here 
[DorisWriterITCase.scala#L336-L343](https://github.com/apache/doris-spark-connector/blob/master/spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/sql/DorisWriterITCase.scala#L336-L343)
```scala
Thread.sleep(10000)
      val actual = ContainerUtils.executeSQLStatement(
        getDorisQueryConnection,
        LOG,
        String.format("select * from %s.%s", DATABASE, TABLE_JSON_TBL_OVERWRITE),
        2)
      val expected = util.Arrays.asList("doris_tbl,1", "spark_tbl,2");
      checkResultInAnyOrder("testSQLSinkOverwrite", expected.toArray, actual.toArray)
```

File: spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/sql/DorisAnySchemaITCase.scala [hunk 2]
```diff
@@ -0,0 +1,235 @@
...
+         | "doris.sink.properties.partial_columns" = "true",
+         | "doris.write.fields" = "siteid,citycode,username"
+         |)
+         |""".stripMargin)
+
+    spark.sql(
+      """
+        |insert into test_lh(siteid,citycode,username) values (0, 0, "user1"), (1, 0, "user2")
+        |""".stripMargin)
+    spark.stop()
```
Comment (JNSimba) [inline spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/sql/DorisAnySchemaITCase.scala:175]: It is best to put it in finally. Otherwise, after the case fails to execute, `spark.stop` will not be executed, which may cause errors later.

File: spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/sql/DorisAnySchemaITCase.scala [hunk 3]
```diff
@@ -213,8 +213,12 @@ class DorisAnySchemaITCase extends AbstractContainerTestBase {
...
     try {
       val version = spark.version
-      if (StringUtils.startsWith(version, "2")) {
-        LOG.warn("sql partial_columns is only support in spark3+")
+      LOG.info("spark version: " + version)
+      if (StringUtils.startsWith(version, "2")
+        || StringUtils.startsWith(version, "3.1")
+        || StringUtils.startsWith(version, "3.2")
+        || StringUtils.startsWith(version, "3.4")) {
+        LOG.warn("sql partial_columns is only support in spark3.3/3.5+")
```
Comment (JNSimba) [inline spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/sql/DorisAnySchemaITCase.scala:221]: 3.1/3.2/3.4 are not OK?

Comment (wanggx) [reply spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/sql/DorisAnySchemaITCase.scala:221]: yes，I test it。

Comment (JNSimba) [reply spark-doris-connector/spark-doris-connector-it/src/test/java/org/apache/doris/spark/sql/DorisAnySchemaITCase.scala:221]: Yes, I confirmed that only SparkSQL is affected.
In addition, after Spark 3.3+, `insert into table select 1,2` can also update some columns.

**Review by JNSimba — APPROVED** [review]
LGTM
